# Based on Node 10.x LTS image
FROM node:10.15.1-alpine

# Set the default directory where CMD will execute
WORKDIR /app

# Set the default command to execute when creating a new container
CMD ["/bin/bash", "-c", "npm install && npm run dev"]

# Install system requirements
RUN apk add --no-cache build-base python bash

# Copy the README so that it can be shown in the AssignmentPage
COPY README.md /
